#immutable
my_tuple=(1,"amrit",9.7)
print(my_tuple)
my_tuple=("ashmit",[4,6,7],(9,7,3))
print(my_tuple)
my_tuple=4,6,7,"pratham"
print(my_tuple)
#concatenation
print((3,5,7)+(8,98,3))
fruits=("a",'p',"p",'l','e','e')
print(fruits.count('p'))
print(fruits.count('a'))